"""Executable deep tests — device_identity.py.

Source : py_modules/unifideck/security/device_identity.py
Fiche  : OP-38d   Critical — coverage floor 95%.

Generated by deep introspection: the module is imported and
its public surface exercised for real with lightweight
doubles. Zero-arg methods are executed (sync & async),
degraded string inputs are probed, and every remaining
public callable carries a signature/contract assertion.
Hand-deepen the `pytest.skip`-guarded spots to push branch
coverage to the 95% critical floor.
"""
from __future__ import annotations

import inspect

import pytest

import unifideck.security.device_identity as target



class _FakeBus:
    def __init__(self):
        self.emitted = []

    async def emit(self, name, **kw):
        self.emitted.append((name, kw))

    def subscribe(self, *a, **k):
        return None

    def on(self, *a, **k):
        def _d(fn):
            return fn
        return _d


class _FakeCache:
    def __init__(self):
        self._d = {}

    def get(self, key, default=None):
        return self._d.get(key, default)

    def set(self, key, value, *a, **k):
        self._d[key] = value

    def delete(self, key):
        self._d.pop(key, None)


def _mk(cls):
    """Best-effort real instance of cls, or None."""
    import inspect as _i
    try:
        sig = _i.signature(cls.__init__)
    except (ValueError, TypeError):
        try:
            return cls()
        except Exception:
            return None
    kw = {}
    for n, p in sig.parameters.items():
        if n == "self" or p.kind in (
                p.VAR_POSITIONAL, p.VAR_KEYWORD):
            continue
        if p.default is not _i.Parameter.empty:
            kw[n] = p.default if p.default is not None                 else None
            continue
        low = n.lower()
        if "bus" in low:
            kw[n] = _FakeBus()
        elif "cache" in low:
            kw[n] = _FakeCache()
        else:
            kw[n] = None
    try:
        return cls(**kw)
    except Exception:
        return None



def test_module_imports() -> None:
    """Module imports cleanly."""
    assert target.__name__ == 'unifideck.security.device_identity'


def test_DeviceIdentityError_is_class() -> None:
    """`DeviceIdentityError` is importable as a class."""
    assert inspect.isclass(target.DeviceIdentityError)


@pytest.fixture()
def deviceidentityerror_obj():
    """A real DeviceIdentityError — a RuntimeError subclass
    built with a message; explicit build replaces the _mk
    skip-guard."""
    return target.DeviceIdentityError("cannot read")


def test_DeviceIdentityError_instantiates(
    deviceidentityerror_obj,
) -> None:
    """DeviceIdentityError builds and is a RuntimeError."""
    assert isinstance(
        deviceidentityerror_obj,
        target.DeviceIdentityError)
    assert isinstance(
        deviceidentityerror_obj, RuntimeError)


def test_DeviceIdentity_is_class() -> None:
    """`DeviceIdentity` is importable as a class."""
    assert inspect.isclass(target.DeviceIdentity)


@pytest.fixture()
def deviceidentity_obj(tmp_path):
    """A real DeviceIdentity pointed at a temp machine-id
    file holding a valid 32-char hex value, so read()
    succeeds deterministically (no skip, no /etc access)."""
    mid = tmp_path / "machine-id"
    mid.write_text(
        "0123456789abcdef0123456789abcdef\n")
    return target.DeviceIdentity(str(mid))


def test_DeviceIdentity_instantiates(
    deviceidentity_obj,
) -> None:
    """DeviceIdentity builds with an explicit path."""
    assert isinstance(
        deviceidentity_obj, target.DeviceIdentity)


def test_DeviceIdentity_read(
    deviceidentity_obj,
) -> None:
    """`read()` returns the normalised 32-hex value."""
    assert deviceidentity_obj.read() == \
        "0123456789abcdef0123456789abcdef"


def test_FakeDeviceIdentity_is_class() -> None:
    """`FakeDeviceIdentity` is importable as a class."""
    assert inspect.isclass(target.FakeDeviceIdentity)


@pytest.fixture()
def fakedeviceidentity_obj():
    """A real FakeDeviceIdentity built with a valid 32-char
    hex machine-id (its constructor validates the format and
    raises ValueError otherwise — the generic _mk helper
    can't supply a valid value, hence an explicit fixture)."""
    return target.FakeDeviceIdentity(
        "0123456789abcdef0123456789abcdef")


def test_FakeDeviceIdentity_instantiates(
    fakedeviceidentity_obj,
) -> None:
    """FakeDeviceIdentity builds with a valid hex value."""
    assert isinstance(
        fakedeviceidentity_obj,
        target.FakeDeviceIdentity)


def test_FakeDeviceIdentity_read(
    fakedeviceidentity_obj,
) -> None:
    """`read()` returns the fixed value, normalised to
    lowercase, on every call."""
    assert fakedeviceidentity_obj.read() == \
        "0123456789abcdef0123456789abcdef"
    # deterministic across calls
    assert fakedeviceidentity_obj.read() == \
        fakedeviceidentity_obj.read()


def test_FakeDeviceIdentity_rejects_invalid() -> None:
    """The constructor rejects a non-32-hex value."""
    with pytest.raises(ValueError, match="32-char hex"):
        target.FakeDeviceIdentity("too-short")

