import { describe, expect, it } from "vitest";

import { LOCALE_RESOURCES, type SupportedLanguage } from "../../i18n/locales.generated";
import { buildInfoLine } from "./infoLine";

describe("buildInfoLine", () => {
  it("separates the genres the way the panel always has", () => {
    expect(buildInfoLine(["Action", "Indie"], "")).toBe("Action • Indie");
  });

  it("appends the Proton note after the genres", () => {
    expect(buildInfoLine(["Action"], "Runs on GE-Proton7-55")).toBe(
      "Action • Runs on GE-Proton7-55",
    );
  });

  it("does not open with a separator when a game has no genres", () => {
    // Store metadata is often thin for non-Steam titles.
    expect(buildInfoLine([], "Runs on GE-Proton7-55")).toBe("Runs on GE-Proton7-55");
  });

  it("does not end with a separator when no Proton was chosen", () => {
    expect(buildInfoLine(["Action", "Indie"], "")).not.toMatch(/•\s*$/);
  });

  it("is empty when there is nothing to say, so the row can be hidden", () => {
    expect(buildInfoLine([], "")).toBe("");
  });
});

describe("the Proton note's translations", () => {
  // Driven off the generated catalog rather than a list written here, so
  // a language added to defaults/config.json is covered the day it ships
  // instead of the day someone remembers this file.
  const locales = Object.entries(LOCALE_RESOURCES);

  it.each(locales)("%s has the note at all", (_tag, resource) => {
    // Missing keys fall back to en-US, which reads as "the feature is
    // broken in my language" rather than as a missing translation.
    expect(panelOf(resource).protonInUse).toBeTruthy();
  });

  it.each(locales)("%s keeps the {{proton}} placeholder", (_tag, resource) => {
    // Translations are re-generated by DeepL at build time, and a
    // translator — human or machine — dropping the placeholder leaves a
    // sentence that never names a Proton.
    expect(panelOf(resource).protonInUse).toContain("{{proton}}");
  });
});

function panelOf(resource: (typeof LOCALE_RESOURCES)[SupportedLanguage]): {
  protonInUse: string;
} {
  return (resource.translation as { gameInfoPanel: { protonInUse: string } }).gameInfoPanel;
}
